### ISSUE TITLE
Nowy remont - Exception

### ISSUE THREAD

**Issue by wsx22** [balrog-kun/remonty#1]
Chcę zgłosić remont drogi którego nie ma obecnie oznaczonego w danych OSM

wchodzę na: http://remonty.openstreetmap.pl/remonty/issue?@template=item
uzupełniam:
mapa permalink: https://www.openstreetmap.org/#map=16/51.2034/19.3113
Stan: w-trakcie-do-poprawienia
Daty: brak
Link: https://www.kleszczow.pl/aktualnosci/informacja-o-zmianach-w-organizacji-ruchu/
Opis:
Droga https://www.openstreetmap.org/way/198861630  fizycznie nieprzejezdna (w trakcie przebudowy)
Skrzyżowanie https://www.openstreetmap.org/node/686214331 oznaczone znakiem zakazu ruchu z adnotacją nie dotyczy dojazdów do posesji (od stron: północ, południe i wschód). Obecnie fizycznie przejezdne.
klikam [Submit New Entry]

W wyniku zawsze dostaję stronę błędu jak w załączniku.
[issue-201806042146.htm.txt](https://github.com/balrog-kun/remonty/files/2069787/issue-201806042146.htm.txt)
Wynik jest taki sam dla wielu prób z wieloma kombinacjami danych wejściowych.

**Comment by balrog-kun** [comment]
Wygląda na to, że nie wszędzie w naszym kodzie zostały zaktualizowane adresy API OSM kiedy przestali obsługiwać nieszyfrowane HTTP.  Postaram się niedługo poprawić.  Sorry za kłopot.

**Comment by balrog-kun** [comment]
Powinno teraz działać lepiej, prośba o potwierdzenie.  Połączenie z nominatim będzie szło przez https.

**Comment by wsx22** [comment]
Niestety, nadal jest taki sam problem.
[issue-201806052105.htm.txt](https://github.com/balrog-kun/remonty/files/2073633/issue-201806052105.htm.txt)

**Comment by balrog-kun** [comment]
No to teraz powinno być lepiej, zapomniałem przeładować aplikację.

**Comment by wsx22** [comment]
Teraz działa ok.
(poprawnie dodałem nowy remont: http://remonty.openstreetmap.pl/remonty/issue852 )
Zgłoszenie do zamknięcia.
